### ISSUE TITLE
Clarification: package uses onExtensionStart (not chrome.runtime.onInstalled)

### ISSUE THREAD

**Issue by twschiller** [bfred-it/webext-inject-on-install#16]
Context
---
- From the package name, it seems this package should run on extension installation. However, this package uses the custom [onExtensionStart event](https://github.com/fregante/webext-events/blob/main/source/on-extension-start.md), which runs on extension start
- Chrome has an [chrome.runtime.onInstalled](https://developer.chrome.com/docs/extensions/reference/api/runtime#event-onInstalled) event that runs "when the extension is first installed, when the extension is updated to a new version, and when Chrome is updated to a new version."
- It sounds like the package is behaving as intended, and that it runs on startup not just installation? (But not on MV3 worker recycle?)

**Comment by fregante** [comment]
Yeah the package name is not a 100% match. The purpose of the package is to have the content script available when the extension is running. This means:

- on install
- on re-enable
- on update

Also see a related request to bring this behavior to Chrome: 

- https://github.com/w3c/webextensions/issues/617

Are you seeing issues with the MV3 restart? That should have been fixed by https://github.com/fregante/webext-inject-on-install/pull/9

**Comment by twschiller** [comment]
> Are you seeing issues with the MV3 restart? 

We're seeing reinjection on extension reload, which I wasn't expecting from reading the code, given the name of the package. So just figured I'd raise in case anyone else comes across this behavior

**Comment by fregante** [comment]
> reinjection on extension reload

Yes, that's expected. The content script in pixiebrix is deactivated before the reload (onContextInvalidated) so a new one needs to be injected in order to receive messages, restore menuitems and the various triggers. This is not MV3 specific. 

If you're seeing reinjection when *the service worker* reloads, I should look into #9 again.

**Comment by twschiller** [comment]
> Yes, that's expected. The content script in pixiebrix is deactivated before the reload (onContextInvalidated) so a new one needs to be injected in order to receive messages, restore menuitems and the various triggers. This is not MV3 specific.

👍 It was causing a race condition on code that was assumed to run on the next tab to be opened/redirected (and not all existing tabs). We added a fix to address the injection into existing tabs/frames

**Comment by fregante** [comment]
Can you point me to the ticket/PR? I'm not following the sequence of events that leads to the race condition.

All tabs will get the content script in PB, whether via this module or natively via the manifest. PB also protects itself from duplicate injections so I think that shouldn't be an issue either (even if ideally it shouldn't happen at all)

**Comment by twschiller** [comment]
> PB also protects itself from duplicate injections so I think that shouldn't be an issue either (even if ideally it shouldn't happen at all)

There were/are parts of the codebase (e.g., mod activation from marketplace activation links) that were not properly considering content script injection on extension reload. (IIRC, you only considered UI elements with the context invalidation work/startup work)

We handled one of the race condition/injection bugs here: https://github.com/pixiebrix/pixiebrix-extension/pull/8502

There's nothing to look at, on our side we just need to double-check assumptions about injection order
